/* The following code was generated by JFlex 1.6.1 */

/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>MicroR.jflex</tt>
 */
class MicroRLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED =
    "\11\0\1\1\1\3\1\4\1\4\1\4\22\0\1\1\1\21\1\36"+
    "\1\2\2\0\1\20\1\0\1\15\1\16\1\25\1\24\1\27\1\11"+
    "\1\42\1\26\12\7\1\0\1\12\1\10\1\22\1\23\2\0\13\5"+
    "\1\37\5\5\1\43\10\5\4\0\1\6\1\0\1\47\1\5\1\34"+
    "\1\54\1\35\1\44\1\53\1\52\1\40\2\5\1\50\1\46\1\45"+
    "\1\31\1\55\1\5\1\33\1\30\1\41\1\32\1\5\1\51\3\5"+
    "\1\13\1\17\1\14\7\0\1\4\44\0\1\5\12\0\1\5\4\0"+
    "\1\5\5\0\27\5\1\0\37\5\1\0\u01ca\5\4\0\14\5\16\0"+
    "\5\5\7\0\1\5\1\0\1\5\201\0\5\5\1\0\2\5\2\0"+
    "\4\5\1\0\1\5\6\0\1\5\1\0\3\5\1\0\1\5\1\0"+
    "\24\5\1\0\123\5\1\0\213\5\10\0\246\5\1\0\46\5\2\0"+
    "\1\5\7\0\47\5\110\0\33\5\5\0\3\5\55\0\53\5\25\0"+
    "\12\7\4\0\2\5\1\0\143\5\1\0\1\5\17\0\2\5\7\0"+
    "\2\5\12\7\3\5\2\0\1\5\20\0\1\5\1\0\36\5\35\0"+
    "\131\5\13\0\1\5\16\0\12\7\41\5\11\0\2\5\4\0\1\5"+
    "\5\0\26\5\4\0\1\5\11\0\1\5\3\0\1\5\27\0\31\5"+
    "\107\0\23\5\121\0\66\5\3\0\1\5\22\0\1\5\7\0\12\5"+
    "\4\0\12\7\1\0\20\5\4\0\10\5\2\0\2\5\2\0\26\5"+
    "\1\0\7\5\1\0\1\5\3\0\4\5\3\0\1\5\20\0\1\5"+
    "\15\0\2\5\1\0\3\5\4\0\12\7\2\5\23\0\6\5\4\0"+
    "\2\5\2\0\26\5\1\0\7\5\1\0\2\5\1\0\2\5\1\0"+
    "\2\5\37\0\4\5\1\0\1\5\7\0\12\7\2\0\3\5\20\0"+
    "\11\5\1\0\3\5\1\0\26\5\1\0\7\5\1\0\2\5\1\0"+
    "\5\5\3\0\1\5\22\0\1\5\17\0\2\5\4\0\12\7\25\0"+
    "\10\5\2\0\2\5\2\0\26\5\1\0\7\5\1\0\2\5\1\0"+
    "\5\5\3\0\1\5\36\0\2\5\1\0\3\5\4\0\12\7\1\0"+
    "\1\5\21\0\1\5\1\0\6\5\3\0\3\5\1\0\4\5\3\0"+
    "\2\5\1\0\1\5\1\0\2\5\3\0\2\5\3\0\3\5\3\0"+
    "\14\5\26\0\1\5\25\0\12\7\25\0\10\5\1\0\3\5\1\0"+
    "\27\5\1\0\20\5\3\0\1\5\32\0\2\5\6\0\2\5\4\0"+
    "\12\7\25\0\10\5\1\0\3\5\1\0\27\5\1\0\12\5\1\0"+
    "\5\5\3\0\1\5\40\0\1\5\1\0\2\5\4\0\12\7\1\0"+
    "\2\5\22\0\10\5\1\0\3\5\1\0\51\5\2\0\1\5\20\0"+
    "\1\5\21\0\2\5\4\0\12\7\12\0\6\5\5\0\22\5\3\0"+
    "\30\5\1\0\11\5\1\0\1\5\2\0\7\5\37\0\12\7\21\0"+
    "\60\5\1\0\2\5\14\0\7\5\11\0\12\7\47\0\2\5\1\0"+
    "\1\5\2\0\2\5\1\0\1\5\2\0\1\5\6\0\4\5\1\0"+
    "\7\5\1\0\3\5\1\0\1\5\1\0\1\5\2\0\2\5\1\0"+
    "\4\5\1\0\2\5\11\0\1\5\2\0\5\5\1\0\1\5\11\0"+
    "\12\7\2\0\4\5\40\0\1\5\37\0\12\7\26\0\10\5\1\0"+
    "\44\5\33\0\5\5\163\0\53\5\24\0\1\5\12\7\6\0\6\5"+
    "\4\0\4\5\3\0\1\5\3\0\2\5\7\0\3\5\4\0\15\5"+
    "\14\0\1\5\1\0\12\7\6\0\46\5\1\0\1\5\5\0\1\5"+
    "\2\0\53\5\1\0\u014d\5\1\0\4\5\2\0\7\5\1\0\1\5"+
    "\1\0\4\5\2\0\51\5\1\0\4\5\2\0\41\5\1\0\4\5"+
    "\2\0\7\5\1\0\1\5\1\0\4\5\2\0\17\5\1\0\71\5"+
    "\1\0\4\5\2\0\103\5\45\0\20\5\20\0\125\5\14\0\u026c\5"+
    "\2\0\21\5\1\0\32\5\5\0\113\5\6\0\10\5\7\0\15\5"+
    "\1\0\4\5\16\0\22\5\16\0\22\5\16\0\15\5\1\0\3\5"+
    "\17\0\64\5\43\0\1\5\4\0\1\5\3\0\12\7\46\0\12\7"+
    "\6\0\130\5\10\0\51\5\1\0\1\5\5\0\106\5\12\0\37\5"+
    "\47\0\12\7\36\5\2\0\5\5\13\0\54\5\25\0\7\5\10\0"+
    "\12\7\46\0\27\5\11\0\65\5\53\0\12\7\6\0\12\7\15\0"+
    "\1\5\135\0\57\5\21\0\7\5\4\0\12\7\51\0\36\5\15\0"+
    "\2\5\12\7\54\5\32\0\44\5\34\0\12\7\3\0\3\5\12\7"+
    "\44\5\153\0\4\5\1\0\4\5\3\0\2\5\11\0\300\5\100\0"+
    "\u0116\5\2\0\6\5\2\0\46\5\2\0\6\5\2\0\10\5\1\0"+
    "\1\5\1\0\1\5\1\0\1\5\1\0\37\5\2\0\65\5\1\0"+
    "\7\5\1\0\1\5\3\0\3\5\1\0\7\5\3\0\4\5\2\0"+
    "\6\5\4\0\15\5\5\0\3\5\1\0\7\5\53\0\1\4\1\4"+
    "\107\0\1\5\15\0\1\5\20\0\15\5\145\0\1\5\4\0\1\5"+
    "\2\0\12\5\1\0\1\5\3\0\5\5\6\0\1\5\1\0\1\5"+
    "\1\0\1\5\1\0\4\5\1\0\13\5\2\0\4\5\5\0\5\5"+
    "\4\0\1\5\64\0\2\5\u0a7b\0\57\5\1\0\57\5\1\0\205\5"+
    "\6\0\4\5\3\0\2\5\14\0\46\5\1\0\1\5\5\0\1\5"+
    "\2\0\70\5\7\0\1\5\20\0\27\5\11\0\7\5\1\0\7\5"+
    "\1\0\7\5\1\0\7\5\1\0\7\5\1\0\7\5\1\0\7\5"+
    "\1\0\7\5\120\0\1\5\u01d5\0\2\5\52\0\5\5\5\0\2\5"+
    "\4\0\126\5\6\0\3\5\1\0\132\5\1\0\4\5\5\0\51\5"+
    "\3\0\136\5\21\0\33\5\65\0\20\5\u0200\0\u19b6\5\112\0\u51cd\5"+
    "\63\0\u048d\5\103\0\56\5\2\0\u010d\5\3\0\20\5\12\7\2\5"+
    "\24\0\57\5\20\0\37\5\2\0\106\5\61\0\11\5\2\0\147\5"+
    "\2\0\4\5\1\0\36\5\2\0\2\5\105\0\13\5\1\0\3\5"+
    "\1\0\4\5\1\0\27\5\35\0\64\5\16\0\62\5\34\0\12\7"+
    "\30\0\6\5\3\0\1\5\4\0\12\7\34\5\12\0\27\5\31\0"+
    "\35\5\7\0\57\5\34\0\1\5\12\7\6\0\5\5\1\0\12\5"+
    "\12\7\5\5\1\0\51\5\27\0\3\5\1\0\10\5\4\0\12\7"+
    "\6\0\27\5\3\0\1\5\3\0\62\5\1\0\1\5\3\0\2\5"+
    "\2\0\5\5\2\0\1\5\1\0\1\5\30\0\3\5\2\0\13\5"+
    "\7\0\3\5\14\0\6\5\2\0\6\5\2\0\6\5\11\0\7\5"+
    "\1\0\7\5\1\0\53\5\1\0\4\5\4\0\2\5\132\0\43\5"+
    "\15\0\12\7\6\0\u2ba4\5\14\0\27\5\4\0\61\5\u2104\0\u016e\5"+
    "\2\0\152\5\46\0\7\5\14\0\5\5\5\0\1\5\1\0\12\5"+
    "\1\0\15\5\1\0\5\5\1\0\1\5\1\0\2\5\1\0\2\5"+
    "\1\0\154\5\41\0\u016b\5\22\0\100\5\2\0\66\5\50\0\14\5"+
    "\164\0\5\5\1\0\207\5\23\0\12\7\7\0\32\5\6\0\32\5"+
    "\13\0\131\5\3\0\6\5\2\0\6\5\2\0\6\5\2\0\3\5"+
    "\43\0\14\5\1\0\32\5\1\0\23\5\1\0\2\5\1\0\17\5"+
    "\2\0\16\5\42\0\173\5\u0185\0\35\5\3\0\61\5\57\0\40\5"+
    "\20\0\21\5\1\0\10\5\6\0\46\5\12\0\36\5\2\0\44\5"+
    "\4\0\10\5\60\0\236\5\2\0\12\7\126\0\50\5\10\0\64\5"+
    "\234\0\u0137\5\11\0\26\5\12\0\10\5\230\0\6\5\2\0\1\5"+
    "\1\0\54\5\1\0\2\5\3\0\1\5\2\0\27\5\12\0\27\5"+
    "\11\0\37\5\141\0\26\5\12\0\32\5\106\0\70\5\6\0\2\5"+
    "\100\0\1\5\17\0\4\5\1\0\3\5\1\0\33\5\54\0\35\5"+
    "\3\0\35\5\43\0\10\5\1\0\34\5\33\0\66\5\12\0\26\5"+
    "\12\0\23\5\15\0\22\5\156\0\111\5\u03ba\0\65\5\56\0\12\7"+
    "\23\0\55\5\40\0\31\5\7\0\12\7\11\0\44\5\17\0\12\7"+
    "\20\0\43\5\3\0\1\5\14\0\60\5\16\0\4\5\13\0\12\7"+
    "\1\5\45\0\22\5\1\0\31\5\204\0\57\5\21\0\12\7\13\0"+
    "\10\5\2\0\2\5\2\0\26\5\1\0\7\5\1\0\2\5\1\0"+
    "\5\5\3\0\1\5\37\0\5\5\u011e\0\60\5\24\0\2\5\1\0"+
    "\1\5\10\0\12\7\246\0\57\5\121\0\60\5\24\0\1\5\13\0"+
    "\12\7\46\0\53\5\25\0\12\7\u01d6\0\100\5\12\7\25\0\1\5"+
    "\u01c0\0\71\5\u0507\0\u0399\5\u0c67\0\u042f\5\u33d1\0\u0239\5\7\0\37\5"+
    "\1\0\12\7\146\0\36\5\22\0\60\5\20\0\4\5\14\0\12\7"+
    "\11\0\25\5\5\0\23\5\u0370\0\105\5\13\0\1\5\102\0\15\5"+
    "\u4060\0\2\5\u0bfe\0\153\5\5\0\15\5\3\0\11\5\7\0\12\5"+
    "\u1766\0\125\5\1\0\107\5\1\0\2\5\2\0\1\5\2\0\2\5"+
    "\2\0\4\5\1\0\14\5\1\0\1\5\1\0\7\5\1\0\101\5"+
    "\1\0\4\5\2\0\10\5\1\0\7\5\1\0\34\5\1\0\4\5"+
    "\1\0\5\5\1\0\1\5\3\0\7\5\1\0\u0154\5\2\0\31\5"+
    "\1\0\31\5\1\0\37\5\1\0\31\5\1\0\37\5\1\0\31\5"+
    "\1\0\37\5\1\0\31\5\1\0\37\5\1\0\31\5\1\0\10\5"+
    "\2\0\62\7\u1000\0\305\5\u053b\0\4\5\1\0\33\5\1\0\2\5"+
    "\1\0\1\5\2\0\1\5\1\0\12\5\1\0\4\5\1\0\1\5"+
    "\1\0\1\5\6\0\1\5\4\0\1\5\1\0\1\5\1\0\1\5"+
    "\1\0\3\5\1\0\2\5\1\0\1\5\2\0\1\5\1\0\1\5"+
    "\1\0\1\5\1\0\1\5\1\0\1\5\1\0\2\5\1\0\1\5"+
    "\2\0\4\5\1\0\7\5\1\0\4\5\1\0\4\5\1\0\1\5"+
    "\1\0\12\5\1\0\21\5\5\0\3\5\1\0\5\5\1\0\21\5"+
    "\u1144\0\ua6d7\5\51\0\u1035\5\13\0\336\5\u3fe2\0\u021e\5\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05f0\0";

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\2\1\1\14\1\1\1\15"+
    "\1\16\1\17\1\20\1\21\4\3\1\1\11\3\1\0"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\4\3"+
    "\1\0\1\31\15\3\1\0\4\3\1\0\1\3\1\0"+
    "\6\3\1\32\1\33\1\0\1\34\1\3\1\35\1\36"+
    "\1\0\2\3\1\37\4\3\1\0\1\3\1\0\1\3"+
    "\1\40\1\41\1\42\1\43\1\3\1\0\1\3\1\0"+
    "\2\3\1\0\1\3\1\0\1\3\1\44\1\45\1\46"+
    "\1\0\1\3\1\0\1\3\2\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\56\0\134\0\212\0\270\0\346\0\56"+
    "\0\56\0\56\0\56\0\56\0\56\0\u0114\0\u0142\0\u0170"+
    "\0\u019e\0\u01cc\0\56\0\56\0\56\0\56\0\u01fa\0\u0228"+
    "\0\u0256\0\u0284\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398"+
    "\0\u03c6\0\u03f4\0\u0422\0\u0450\0\u047e\0\56\0\56\0\56"+
    "\0\56\0\56\0\56\0\56\0\u04ac\0\u04da\0\u0508\0\u0536"+
    "\0\u0564\0\212\0\u0592\0\u05c0\0\u05ee\0\u061c\0\u064a\0\u0678"+
    "\0\u06a6\0\u06d4\0\u0702\0\u0730\0\u075e\0\u078c\0\u07ba\0\u07e8"+
    "\0\u0816\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\u0958"+
    "\0\u0986\0\u09b4\0\u09e2\0\u0a10\0\u0a3e\0\212\0\212\0\u0a6c"+
    "\0\212\0\u0a9a\0\212\0\212\0\u0ac8\0\u0af6\0\u0b24\0\212"+
    "\0\u0b52\0\u0b80\0\u0bae\0\u0bdc\0\u0c0a\0\u0c38\0\u0c66\0\u0c94"+
    "\0\212\0\212\0\212\0\212\0\u0cc2\0\u0cf0\0\u0d1e\0\u0d4c"+
    "\0\u0d7a\0\u0da8\0\u0dd6\0\u0e04\0\u0e32\0\u0e60\0\212\0\56"+
    "\0\212\0\u0e8e\0\u0ebc\0\u0eea\0\u0f18\0\56\0\212";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\3\1\0\1\5\1\2\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\2\5\1\30\1\31\1\32\1\33\1\5\1\34"+
    "\1\35\1\2\1\5\1\36\1\37\1\40\1\41\1\5"+
    "\1\42\1\43\2\5\1\44\56\0\3\4\2\0\51\4"+
    "\5\0\1\5\1\45\1\5\20\0\6\5\1\0\3\5"+
    "\1\0\13\5\7\0\1\6\57\0\1\46\10\0\1\47"+
    "\52\0\1\50\56\0\1\51\57\0\1\52\55\0\1\53"+
    "\55\0\1\54\40\0\1\5\1\45\1\5\20\0\1\5"+
    "\1\55\4\5\1\0\3\5\1\0\13\5\5\0\1\5"+
    "\1\45\1\5\20\0\5\5\1\56\1\0\3\5\1\0"+
    "\13\5\5\0\1\5\1\45\1\5\20\0\1\5\1\57"+
    "\4\5\1\0\3\5\1\0\13\5\5\0\1\5\1\45"+
    "\1\5\20\0\6\5\1\0\3\5\1\0\5\5\1\60"+
    "\5\5\37\0\1\61\23\0\1\5\1\45\1\5\20\0"+
    "\6\5\1\0\3\5\1\0\1\5\1\62\11\5\5\0"+
    "\1\5\1\45\1\5\20\0\6\5\1\0\3\5\1\0"+
    "\4\5\1\63\6\5\5\0\1\5\1\45\1\5\20\0"+
    "\2\5\1\64\3\5\1\0\3\5\1\0\13\5\5\0"+
    "\1\5\1\45\1\5\20\0\2\5\1\65\3\5\1\0"+
    "\3\5\1\0\13\5\5\0\1\5\1\45\1\5\20\0"+
    "\6\5\1\0\3\5\1\0\4\5\1\66\6\5\5\0"+
    "\1\5\1\45\1\5\20\0\1\67\5\5\1\0\3\5"+
    "\1\0\13\5\5\0\1\5\1\45\1\5\20\0\6\5"+
    "\1\0\3\5\1\0\7\5\1\70\3\5\5\0\1\5"+
    "\1\45\1\5\20\0\5\5\1\71\1\0\3\5\1\0"+
    "\13\5\5\0\1\5\1\45\1\5\20\0\3\5\1\72"+
    "\2\5\1\0\3\5\1\0\13\5\5\0\1\5\1\0"+
    "\1\5\20\0\6\5\1\0\3\5\1\0\13\5\5\0"+
    "\1\5\1\45\1\5\20\0\2\5\1\73\3\5\1\0"+
    "\3\5\1\0\13\5\5\0\1\5\1\45\1\5\20\0"+
    "\6\5\1\0\2\5\1\74\1\0\4\5\1\75\6\5"+
    "\5\0\1\5\1\45\1\5\20\0\6\5\1\0\3\5"+
    "\1\0\2\5\1\76\10\5\5\0\1\5\1\45\1\5"+
    "\20\0\1\77\5\5\1\0\3\5\1\0\13\5\40\0"+
    "\1\100\22\0\1\5\1\45\1\5\20\0\6\5\1\0"+
    "\1\5\1\101\1\5\1\0\13\5\5\0\1\5\1\45"+
    "\1\5\20\0\6\5\1\0\3\5\1\0\2\5\1\102"+
    "\10\5\5\0\1\5\1\45\1\5\20\0\6\5\1\0"+
    "\3\5\1\0\5\5\1\103\5\5\5\0\1\5\1\45"+
    "\1\5\20\0\6\5\1\0\1\5\1\104\1\5\1\0"+
    "\13\5\3\105\2\0\1\106\1\107\1\106\20\105\6\106"+
    "\1\105\3\106\1\105\13\106\5\0\1\5\1\45\1\5"+
    "\20\0\6\5\1\0\1\5\1\110\1\5\1\0\13\5"+
    "\5\0\1\5\1\45\1\5\20\0\6\5\1\0\3\5"+
    "\1\0\4\5\1\111\6\5\5\0\1\5\1\45\1\5"+
    "\20\0\6\5\1\0\1\5\1\112\1\5\1\0\13\5"+
    "\5\0\1\5\1\45\1\5\20\0\3\5\1\113\2\5"+
    "\1\0\3\5\1\0\13\5\5\0\1\5\1\45\1\5"+
    "\20\0\2\5\1\114\3\5\1\0\3\5\1\0\13\5"+
    "\5\0\1\5\1\45\1\5\20\0\6\5\1\0\3\5"+
    "\1\0\11\5\1\115\1\5\5\0\1\5\1\45\1\5"+
    "\20\0\1\116\5\5\1\0\3\5\1\0\13\5\5\0"+
    "\1\5\1\45\1\5\20\0\5\5\1\117\1\0\3\5"+
    "\1\0\13\5\30\0\1\120\32\0\1\5\1\45\1\5"+
    "\20\0\6\5\1\0\3\5\1\0\5\5\1\121\5\5"+
    "\5\0\1\5\1\45\1\5\20\0\4\5\1\122\1\5"+
    "\1\0\3\5\1\0\13\5\5\0\1\5\1\45\1\5"+
    "\20\0\6\5\1\0\3\5\1\0\5\5\1\123\5\5"+
    "\5\0\1\5\1\45\1\5\20\0\6\5\1\0\3\5"+
    "\1\0\2\5\1\124\10\5\40\0\1\125\22\0\1\5"+
    "\1\45\1\5\20\0\6\5\1\0\1\5\1\126\1\5"+
    "\1\0\13\5\5\0\1\5\1\0\1\5\20\0\6\5"+
    "\1\0\1\5\1\126\1\5\1\0\13\5\5\0\1\5"+
    "\1\45\1\5\20\0\6\5\1\0\3\5\1\0\5\5"+
    "\1\127\5\5\5\0\1\5\1\45\1\5\20\0\6\5"+
    "\1\0\3\5\1\0\11\5\1\130\1\5\5\0\1\5"+
    "\1\45\1\5\20\0\6\5\1\0\3\5\1\0\2\5"+
    "\1\131\10\5\5\0\1\5\1\45\1\5\20\0\4\5"+
    "\1\132\1\5\1\0\3\5\1\0\13\5\5\0\1\5"+
    "\1\45\1\5\20\0\3\5\1\133\2\5\1\0\3\5"+
    "\1\0\13\5\5\0\1\5\1\45\1\5\20\0\6\5"+
    "\1\0\3\5\1\0\5\5\1\134\5\5\41\0\1\135"+
    "\21\0\1\5\1\45\1\5\20\0\6\5\1\0\2\5"+
    "\1\136\1\0\13\5\45\0\1\137\15\0\1\5\1\45"+
    "\1\5\20\0\6\5\1\0\3\5\1\0\2\5\1\140"+
    "\10\5\5\0\1\5\1\45\1\5\20\0\5\5\1\141"+
    "\1\0\3\5\1\0\13\5\5\0\1\5\1\45\1\5"+
    "\20\0\6\5\1\0\2\5\1\142\1\0\13\5\5\0"+
    "\1\5\1\45\1\5\20\0\5\5\1\143\1\0\3\5"+
    "\1\0\13\5\5\0\1\5\1\45\1\5\20\0\6\5"+
    "\1\0\3\5\1\0\2\5\1\144\10\5\5\0\1\5"+
    "\1\45\1\5\20\0\6\5\1\0\1\5\1\145\1\5"+
    "\1\0\13\5\42\0\1\146\20\0\1\5\1\45\1\5"+
    "\20\0\6\5\1\0\1\5\1\147\1\5\1\0\13\5"+
    "\41\0\1\150\21\0\1\5\1\45\1\5\20\0\6\5"+
    "\1\0\2\5\1\151\1\0\13\5\5\0\1\5\1\45"+
    "\1\5\20\0\6\5\1\0\3\5\1\0\2\5\1\152"+
    "\10\5\43\0\1\153\17\0\1\5\1\45\1\5\20\0"+
    "\1\5\1\154\4\5\1\0\3\5\1\0\13\5\35\0"+
    "\1\155\25\0\1\5\1\45\1\5\20\0\5\5\1\156"+
    "\1\0\3\5\1\0\13\5\5\0\1\5\1\45\1\5"+
    "\20\0\5\5\1\157\1\0\3\5\1\0\13\5\36\0"+
    "\1\160\24\0\1\5\1\45\1\5\20\0\6\5\1\0"+
    "\3\5\1\0\2\5\1\161\10\5\53\0\1\162\7\0"+
    "\1\5\1\45\1\5\20\0\6\5\1\0\3\5\1\0"+
    "\10\5\1\163\2\5\35\0\1\164\25\0\1\5\1\45"+
    "\1\5\20\0\5\5\1\165\1\0\3\5\1\0\13\5"+
    "\33\0\1\166\27\0\1\5\1\45\1\5\20\0\3\5"+
    "\1\167\2\5\1\0\3\5\1\0\13\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3910];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\6\11\5\1\4\11\16\1\1\0"+
    "\7\11\4\1\1\0\16\1\1\0\4\1\1\0\1\1"+
    "\1\0\10\1\1\0\4\1\1\0\7\1\1\0\1\1"+
    "\1\0\6\1\1\0\1\1\1\0\2\1\1\0\1\1"+
    "\1\0\2\1\1\11\1\1\1\0\1\1\1\0\1\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the
   * matched text
   */
  private int yycolumn;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /**
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	private void echo ()
	{ System . out . print (yytext ()); }

	public int position () { return yycolumn; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  MicroRLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /**
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2466) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	{ return new Token (Symbol . EOF); }
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { echo (); ErrorMessage.print (yycolumn, "Illegal character");
            }
          case 40: break;
          case 2:
            { echo ();
            }
          case 41: break;
          case 3:
            { echo (); return new Token (Symbol.ID, yytext());
            }
          case 42: break;
          case 4:
            { echo (); return new Token (Symbol.INT, yytext());
            }
          case 43: break;
          case 5:
            { echo (); return new Token (Symbol.LT, yytext());
            }
          case 44: break;
          case 6:
            { echo (); return new Token (Symbol.SUB, yytext());
            }
          case 45: break;
          case 7:
            { echo (); return new Token (Symbol.SEMICOLON, yytext());
            }
          case 46: break;
          case 8:
            { echo (); return new Token (Symbol.LBRACE, yytext());
            }
          case 47: break;
          case 9:
            { echo (); return new Token (Symbol.RBRACE, yytext());
            }
          case 48: break;
          case 10:
            { echo (); return new Token (Symbol.LPARA, yytext());
            }
          case 49: break;
          case 11:
            { echo (); return new Token (Symbol.RPARA, yytext());
            }
          case 50: break;
          case 12:
            { echo (); return new Token (Symbol.CNOT, yytext());
            }
          case 51: break;
          case 13:
            { echo (); return new Token (Symbol.GT, yytext());
            }
          case 52: break;
          case 14:
            { echo (); return new Token (Symbol.ADD, yytext());
            }
          case 53: break;
          case 15:
            { echo (); return new Token (Symbol.MULT, yytext());
            }
          case 54: break;
          case 16:
            { echo (); return new Token (Symbol.DIV, yytext());
            }
          case 55: break;
          case 17:
            { echo (); return new Token (Symbol.COMMA, yytext());
            }
          case 56: break;
          case 18:
            { echo (); return new Token (Symbol.ASSIGN, yytext());
            }
          case 57: break;
          case 19:
            { echo (); return new Token (Symbol.LE, yytext());
            }
          case 58: break;
          case 20:
            { echo (); return new Token (Symbol.COR, yytext());
            }
          case 59: break;
          case 21:
            { echo (); return new Token (Symbol.CAND, yytext());
            }
          case 60: break;
          case 22:
            { echo (); return new Token (Symbol.NE, yytext());
            }
          case 61: break;
          case 23:
            { echo (); return new Token (Symbol.EQ, yytext());
            }
          case 62: break;
          case 24:
            { echo (); return new Token (Symbol.GE, yytext());
            }
          case 63: break;
          case 25:
            { echo (); return new Token (Symbol.IF, yytext());
            }
          case 64: break;
          case 26:
            { echo (); return new Token (Symbol.CON, yytext());
            }
          case 65: break;
          case 27:
            { echo (); return new Token (Symbol.ELSE, yytext());
            }
          case 66: break;
          case 28:
            { echo (); return new Token (Symbol.TAIL, yytext());
            }
          case 67: break;
          case 29:
            { echo (); return new Token (Symbol.NULL, yytext());
            }
          case 68: break;
          case 30:
            { echo (); return new Token (Symbol.MAIN, yytext());
            }
          case 69: break;
          case 31:
            { echo (); return new Token (Symbol.HEAD, yytext());
            }
          case 70: break;
          case 32:
            { echo (); return new Token (Symbol.WHILE, yytext());
            }
          case 71: break;
          case 33:
            { echo (); return new Token (Symbol.PRINT, yytext());
            }
          case 72: break;
          case 34:
            { echo (); return new Token (Symbol.SOURCE, yytext());
            }
          case 73: break;
          case 35:
            { echo (); return new Token (Symbol.RETURN, yytext());
            }
          case 74: break;
          case 36:
            { echo (); return new Token (Symbol.READ, yytext());
            }
          case 75: break;
          case 37:
            { echo (); return new Token (Symbol.LISTR, yytext());
            }
          case 76: break;
          case 38:
            { echo (); return new Token (Symbol.FUNC, yytext());
            }
          case 77: break;
          case 39:
            { echo (); return new Token (Symbol.ASINT, yytext());
            }
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
